// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 1.0.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// hub75 //
// ----- //

#define hub75_wrap_target 0
#define hub75_wrap 1
#define hub75_pio_version 0

static const uint16_t hub75_program_instructions[] = {
            //     .wrap_target
    0x6006, //  0: out    pins, 6         side 0
    0xb042, //  1: nop                    side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program hub75_program = {
    .instructions = hub75_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = hub75_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config hub75_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + hub75_wrap_target, offset + hub75_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

    static inline void hub75_program_init(PIO pio, unsigned sm, unsigned offset, unsigned base_pin) {
        for (int i = 0; i < 7; ++i) {
            pio_gpio_init(pio, base_pin + i);
        }
        pio_sm_set_consecutive_pindirs(pio, sm, base_pin, 7, true);
        pio_sm_config c = hub75_program_get_default_config(offset);
        sm_config_set_out_pins(&c, base_pin, 6);
        sm_config_set_sideset_pins(&c, base_pin + 6);
        sm_config_set_out_shift(&c, true, true, 6);
        sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
        sm_config_set_clkdiv(&c, 4.f);
        pio_sm_init(pio, sm, offset, &c);
        pio_sm_set_enabled(pio, sm, true);
    }

#endif

